# Generated by Django 5.2.6 on 2025-12-01 08:17

import Intranet.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='calificacion_tributaria',
            fields=[
                ('secuencia_evento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mercado', models.CharField(choices=[('ACCIONES', 'Acciones'), ('RENTA FIJA', 'Renta Fija'), ('DERIVADOS FINANCIEROS', 'Derivados Financieros'), ('FONDOS DE INVERSIÓN-MUTUOS', 'Fondos de Inversión-Mutuos'), ('INSTRUMENTOS DEL BANCO CENTRAL', 'Instrumentos del Banco Central'), ('INSTRUMENTOS DEL ESTADO-TESORERÍA', 'Instrumentos del Estado-Tesorería'), ('MERCADO MONETARIO', 'Mercado Monetario'), ('MERCADO INTERNACIONAL', 'Mercado Internacional'), ('MERCADO BANCARIO-CRÉDITOS', 'Mercado Bancario-Créditos')], max_length=50)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha_pago', models.DateField()),
                ('dividendo', models.IntegerField(blank=True, null=True)),
                ('valor_historico', models.BigIntegerField(blank=True, null=True)),
                ('anio', models.IntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('VALIDADA', 'Validada'), ('RECHAZADA', 'Rechazada')], max_length=30)),
                ('origen_calificacion', models.CharField(choices=[('CORREDOR', 'Corredor'), ('BOLSA', 'Bolsa'), ('SISTEMA', 'Sistema Interno')], default='SISTEMA', max_length=20)),
                ('isfut', models.BooleanField(default=False)),
                ('factor_actualizacion', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('evento_capital', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='instrumento_financiero',
            fields=[
                ('instrumento_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6, unique=True)),
                ('descripcion', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=50)),
                ('bolsa', models.CharField(max_length=30)),
                ('mercado', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='califica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(default=0.0)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.calificacion_tributaria')),
            ],
        ),
        migrations.CreateModel(
            name='categoria_factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Intranet.categoria_factor')),
            ],
        ),
        migrations.CreateModel(
            name='factor_calificacion',
            fields=[
                ('factor_id', models.AutoField(default=8, primary_key=True, serialize=False)),
                ('nombre_factor', models.CharField(max_length=120)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Intranet.categoria_factor')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion_tributaria',
            name='factores',
            field=models.ManyToManyField(through='Intranet.califica', to='Intranet.factor_calificacion'),
        ),
        migrations.AddField(
            model_name='califica',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.factor_calificacion'),
        ),
        migrations.AddField(
            model_name='calificacion_tributaria',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.instrumento_financiero'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', Intranet.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
