# Generated by Django 5.2.6 on 2025-10-27 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rol',
            fields=[
                ('rol_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('usuario_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=512)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.rol')),
            ],
        ),
    ]
