# Generated by Django 5.2.6 on 2025-11-10 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='factor',
            fields=[
                ('factor_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_factor', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='instrumento_financiero',
            fields=[
                ('instrumento_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('descripcion', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=30)),
                ('bolsa', models.CharField(max_length=30)),
                ('mercado', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='rol',
            name='rol_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='calificacion_tributaria',
            fields=[
                ('calificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('mercado', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=150)),
                ('fecha_pago', models.DateField()),
                ('secuencia_evento', models.BigIntegerField()),
                ('dividendo', models.IntegerField(blank=True, null=True)),
                ('valor_historico', models.BigIntegerField(blank=True, null=True)),
                ('anio', models.IntegerField()),
                ('estado', models.CharField(max_length=30)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.rol')),
            ],
        ),
        migrations.CreateModel(
            name='califica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.calificacion_tributaria')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.factor')),
            ],
        ),
        migrations.AddField(
            model_name='calificacion_tributaria',
            name='factores',
            field=models.ManyToManyField(through='Intranet.califica', to='Intranet.factor'),
        ),
        migrations.AddField(
            model_name='calificacion_tributaria',
            name='instrumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.instrumento_financiero'),
        ),
        migrations.CreateModel(
            name='solicitud',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=130)),
                ('fecha', models.DateField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.rol')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.usuario')),
            ],
        ),
    ]
