# Generated by Django 5.2.6 on 2025-11-17 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0002_factor_instrumento_financiero_alter_rol_rol_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='califica',
            name='valor',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='categoria_factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Intranet.categoria_factor')),
            ],
        ),
        migrations.CreateModel(
            name='factor_calificacion',
            fields=[
                ('factor_id', models.AutoField(default=8, primary_key=True, serialize=False)),
                ('nombre_factor', models.CharField(max_length=120)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.categoria_factor')),
            ],
        ),
        migrations.AlterField(
            model_name='califica',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Intranet.factor_calificacion'),
        ),
        migrations.AlterField(
            model_name='calificacion_tributaria',
            name='factores',
            field=models.ManyToManyField(through='Intranet.califica', to='Intranet.factor_calificacion'),
        ),
        migrations.DeleteModel(
            name='factor',
        ),
    ]
