# Generated by Django 5.2.6 on 2025-12-04 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0003_auditoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('calificacion_created', 'Calificación creada'), ('calificacion_updated', 'Calificación actualizada'), ('calificacion_deleted', 'Calificación eliminada'), ('instrumento_created', 'Instrumento creado'), ('instrumento_updated', 'Instrumento actualizado'), ('instrumento_deleted', 'Instrumento eliminado'), ('solicitud_creada', 'Solicitud creada')], max_length=50)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
