# Generated by Django 5.2.6 on 2025-11-17 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0003_alter_califica_valor_categoria_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor_calificacion',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Intranet.categoria_factor'),
        ),
    ]
