# Generated by Django 5.2.6 on 2025-11-17 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0004_alter_factor_calificacion_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento_financiero',
            name='categoria',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='instrumento_financiero',
            name='mercado',
            field=models.CharField(max_length=50),
        ),
    ]
